import assert from "node:assert/strict";
import * as XLSX from "xlsx";
import { describe, it } from "node:test";
import { buildMonthlyAttendanceXlsx } from "./monthly-attendance-report-xlsx.builder";
import type { MonthlyAttendanceReportDataset } from "../types/monthly-attendance-report";

const metrics = { scheduledWorkdays: 1, presentWorkdays: 1, absentWorkdays: 0, justifiedWorkdays: 0, attendanceRate: 100, absenteeismRate: 0, onTimeWorkdays: 1, lateWorkdays: 0, punctualityRate: 100, earlyCheckoutWorkdays: 0, missingCheckinWorkdays: 0, missingCheckoutWorkdays: 0, notifiedUnavailableWorkdays: 0, confirmedButAbsentWorkdays: 0, unannouncedAbsenceWorkdays: 0, pendingReviewAttendances: 0, rejectedAttendances: 0, outsideGeofenceAttendances: 0, workedMinutes: 480, extraWorkedMinutes: 30 };
const dataset = (): MonthlyAttendanceReportDataset => ({ schemaVersion: 1, companyId: "c", period: { year: 2026, month: 9, timezone: "America/Argentina/Buenos_Aires", start: "2026-09-01T03:00:00.000Z", endExclusive: "2026-10-01T03:00:00.000Z" }, evaluatedAt: "2026-10-01T12:00:00.000Z", summary: { ...metrics, totalWorkedMinutes: 780, totalExtraWorkedMinutes: 30 }, employees: [{ employeeId: "e", employeeName: "Ana", ...metrics }, { employeeId: "j", employeeName: "Juan", ...metrics, workedMinutes: 300 }], services: ["A", "B", "C"].map((name, i) => ({ serviceId: `s${i}`, serviceName: name, ...metrics })), incidents: [] });
describe("monthly attendance XLSX builder", () => { it("creates the five required sheets and one Hours row per employee", () => { const workbook = XLSX.read(buildMonthlyAttendanceXlsx(dataset()), { type: "buffer" }); assert.deepEqual(workbook.SheetNames, ["Resumen", "Empleados", "Servicios", "Incidencias", "Horas"]); assert.match(JSON.stringify(XLSX.utils.sheet_to_json(workbook.Sheets.Empleados!, { header: 1 })), /Ana/); assert.equal(XLSX.utils.sheet_to_json(workbook.Sheets.Horas!, { header: 1 }).length, 3); }); });
describe("monthly attendance incident cells", () => { it("uses expected/actual instants and computes late minutes", () => { const d = dataset(); d.incidents = [{ type: "LATE", employeeWorkdayId: "ew", employeeId: "e", employeeName: "Ana", operationWorkdayId: "ow", operationId: "op", serviceId: "s", serviceName: "A", workDate: "2026-09-01", operationShiftId: null, shiftNameSnapshot: null, confirmationStatus: null, expectationStatus: "EXPECTED", effectiveState: "PRESENT", checkInAt: "2026-09-01T12:20:00.000Z", checkOutAt: null, expectedStartAt: "2026-09-01T12:00:00.000Z", expectedEndAt: "2026-09-01T20:00:00.000Z", validationStatus: null, locationStatus: null, punctualityStatus: "LATE", checkoutStatus: null }]; const workbook = XLSX.read(buildMonthlyAttendanceXlsx(d), { type: "buffer" }); const rows = XLSX.utils.sheet_to_json(workbook.Sheets.Incidencias!, { header: 1 }) as unknown[][]; assert.equal(rows[1]?.[6], "2026-09-01T12:00:00.000Z"); assert.equal(rows[1]?.[7], "2026-09-01T12:20:00.000Z"); assert.equal(rows[1]?.[8], 20); }); });
