import type { MonthlyAttendanceReportDataset } from "../types/monthly-attendance-report";
import { escapeHtml } from "../utils/daily-attendance-report-email";

const label = (value: number): string => value.toLocaleString("es-AR");
export const buildMonthlyAttendanceReportEmail = (dataset: MonthlyAttendanceReportDataset, companyName: string) => {
  const period = `${dataset.period.month.toString().padStart(2, "0")}/${dataset.period.year}`;
  const subject = `Reporte mensual de asistencia ${period} — ${companyName}`;
  const s = dataset.summary;
  const attention = dataset.employees.filter((e) => e.lateWorkdays + e.absentWorkdays + e.missingCheckinWorkdays + e.missingCheckoutWorkdays + e.pendingReviewAttendances + e.rejectedAttendances > 0).sort((a, b) => (b.absentWorkdays + b.lateWorkdays) - (a.absentWorkdays + a.lateWorkdays) || a.employeeName.localeCompare(b.employeeName)).slice(0, 10);
  const text = [`Reporte mensual de asistencia`, `Período: ${period}`, "", `Presentismo: ${s.attendanceRate.toFixed(2)}%`, `Presentes: ${label(s.presentWorkdays)} · Ausentes: ${label(s.absentWorkdays)} · Justificadas: ${label(s.justifiedWorkdays)}`, `Tardanzas: ${label(s.lateWorkdays)} · Faltas sin aviso: ${label(s.unannouncedAbsenceWorkdays)}`, `Confirmaron y faltaron: ${label(s.confirmedButAbsentWorkdays)}`, `Pendientes de revisión: ${label(s.pendingReviewAttendances)} · Rechazadas: ${label(s.rejectedAttendances)}`, `Horas adicionales: ${Math.floor(s.extraWorkedMinutes / 60)}h ${s.extraWorkedMinutes % 60}m`, "", "Empleados que requieren atención", ...(attention.length ? attention.map((e) => `- ${e.employeeName}: ${e.absentWorkdays} ausencias, ${e.lateWorkdays} tardanzas`) : ["- No se detectaron incidencias relevantes."]), "", "El detalle completo se encuentra en el archivo XLSX adjunto."] .join("\n");
  const cards = [["Presentismo", `${s.attendanceRate.toFixed(2)}%`], ["Ausencias", label(s.absentWorkdays)], ["Faltas sin aviso", label(s.unannouncedAbsenceWorkdays)], ["Horas adicionales", `${Math.floor(s.extraWorkedMinutes / 60)}h ${s.extraWorkedMinutes % 60}m`]].map(([name, value]) => `<div class="stat"><span>${name}</span><strong>${value}</strong></div>`).join("");
  const rows = attention.map((e) => `<tr><td>${escapeHtml(e.employeeName)}</td><td>${e.absentWorkdays}</td><td>${e.lateWorkdays}</td><td>${e.pendingReviewAttendances + e.rejectedAttendances}</td></tr>`).join("");
  const html = `<html lang="es"><body style="font-family:Arial;color:#1f2937"><h1>Reporte mensual de asistencia</h1><p><strong>${escapeHtml(companyName)}</strong><br>Período: ${escapeHtml(period)}</p><div style="display:flex;gap:8px">${cards}</div><h2>Resumen</h2><p>Se registraron ${s.presentWorkdays} jornadas presentes, ${s.absentWorkdays} ausencias y ${s.lateWorkdays} tardanzas. Las horas adicionales totalizaron ${Math.floor(s.extraWorkedMinutes / 60)}h ${s.extraWorkedMinutes % 60}m.</p><h2>Empleados que requieren atención</h2>${rows ? `<table><tr><th>Empleado</th><th>Ausencias</th><th>Tardanzas</th><th>Revisión</th></tr>${rows}</table>` : "<p>No se detectaron incidencias relevantes.</p>"}<p>El detalle completo está en el archivo XLSX adjunto.</p></body></html>`;
  return { subject, text, html };
};
