export type CompanyPermission =
  | "company:read"
  | "company:settings:update"
  | "users:manage"
  | "employees:read"
  | "employees:manage"
  | "services:read"
  | "services:manage"
  | "operations:read"
  | "operations:manage"
  | "attendance:read"
  | "attendance:review"
  | "attendance:export"
  | "absences:read"
  | "absences:review"
  | "reports:read"
  | "reports:export"
  | "bot_simulator:use";
