import sql from "mssql";
import { getPool } from "../database/connection";
export type MonthlyDelivery = { id: string; email: string; attemptCount: number };
export const monthlyAttendanceReportDeliveryRepository = {
  async count(runId: string, companyId: string): Promise<number> { const r = await getPool().request().input("runId",sql.UniqueIdentifier,runId).input("companyId",sql.UniqueIdentifier,companyId).query("SELECT COUNT(*) total FROM monthly_attendance_report_deliveries WHERE report_run_id=@runId AND company_id=@companyId"); return Number(r.recordset[0]?.total ?? 0); },
  async snapshot(runId: string, companyId: string, recipients: Array<{ id: string; email: string; displayName: string | null }>): Promise<void> {
    const transaction = new sql.Transaction(getPool());
    await transaction.begin();
    try {
      for (const recipient of recipients) await new sql.Request(transaction).input("runId",sql.UniqueIdentifier,runId).input("companyId",sql.UniqueIdentifier,companyId).input("recipientId",sql.UniqueIdentifier,recipient.id).input("email",sql.NVarChar(320),recipient.email).input("name",sql.NVarChar(200),recipient.displayName).query("IF NOT EXISTS (SELECT 1 FROM monthly_attendance_report_deliveries WHERE report_run_id=@runId AND company_id=@companyId AND email_snapshot=@email) INSERT INTO monthly_attendance_report_deliveries(report_run_id,company_id,recipient_id,email_snapshot,display_name_snapshot) VALUES(@runId,@companyId,@recipientId,@email,@name)");
      await transaction.commit();
    } catch (error) { await transaction.rollback(); throw error; }
  },
  async claim(runId: string, companyId: string, owner: string, leaseSeconds: number): Promise<MonthlyDelivery | null> {
    const r = await getPool().request().input("runId",sql.UniqueIdentifier,runId).input("companyId",sql.UniqueIdentifier,companyId).input("owner",sql.NVarChar(100),owner).input("lease",sql.Int,leaseSeconds).query(";WITH next_row AS (SELECT TOP(1) id FROM monthly_attendance_report_deliveries WITH(UPDLOCK,READPAST,ROWLOCK) WHERE report_run_id=@runId AND company_id=@companyId AND ((status IN(N'PENDING',N'FAILED') AND (next_attempt_at IS NULL OR next_attempt_at<=SYSUTCDATETIME())) OR (status=N'PROCESSING' AND lease_expires_at<SYSUTCDATETIME())) ORDER BY created_at) UPDATE d SET status=N'PROCESSING',attempt_count=attempt_count+1,lease_owner=@owner,lease_expires_at=DATEADD(SECOND,@lease,SYSUTCDATETIME()),updated_at=SYSUTCDATETIME() OUTPUT INSERTED.* FROM monthly_attendance_report_deliveries d JOIN next_row n ON n.id=d.id"); const row=r.recordset[0] as Record<string,unknown>|undefined; return row ? {id:String(row.id),email:String(row.email_snapshot),attemptCount:Number(row.attempt_count)} : null;
  },
  async sent(id:string, companyId:string, owner:string, provider:string|null): Promise<void> { await getPool().request().input("id",sql.UniqueIdentifier,id).input("companyId",sql.UniqueIdentifier,companyId).input("owner",sql.NVarChar(100),owner).input("provider",sql.NVarChar(200),provider).query("UPDATE monthly_attendance_report_deliveries SET status=N'SENT',provider_message_id=@provider,lease_owner=NULL,lease_expires_at=NULL,sent_at=SYSUTCDATETIME(),updated_at=SYSUTCDATETIME() WHERE id=@id AND company_id=@companyId AND status=N'PROCESSING' AND lease_owner=@owner"); },
  async failed(id:string, companyId:string, owner:string, error:string, retryAt:Date|null, terminal:boolean): Promise<void> { await getPool().request().input("id",sql.UniqueIdentifier,id).input("companyId",sql.UniqueIdentifier,companyId).input("owner",sql.NVarChar(100),owner).input("error",sql.NVarChar(1000),error).input("retryAt",sql.DateTime2,retryAt).input("status",sql.NVarChar(30),terminal?"FAILED_TERMINAL":"FAILED").query("UPDATE monthly_attendance_report_deliveries SET status=@status,last_error=@error,next_attempt_at=@retryAt,lease_owner=NULL,lease_expires_at=NULL,updated_at=SYSUTCDATETIME() WHERE id=@id AND company_id=@companyId AND status=N'PROCESSING' AND lease_owner=@owner"); },
  async counts(runId:string, companyId:string): Promise<{total:number;sent:number;terminal:number;retryable:number;nextAttemptAt:Date|null}> { const r=await getPool().request().input("runId",sql.UniqueIdentifier,runId).input("companyId",sql.UniqueIdentifier,companyId).query("SELECT COUNT(*) total,SUM(CASE WHEN status=N'SENT' THEN 1 ELSE 0 END) sent,SUM(CASE WHEN status=N'FAILED_TERMINAL' THEN 1 ELSE 0 END) terminal,SUM(CASE WHEN status=N'FAILED' THEN 1 ELSE 0 END) retryable,MIN(CASE WHEN status=N'FAILED' THEN next_attempt_at END) next_attempt_at FROM monthly_attendance_report_deliveries WHERE report_run_id=@runId AND company_id=@companyId"); const row=r.recordset[0]; return {total:Number(row.total),sent:Number(row.sent),terminal:Number(row.terminal),retryable:Number(row.retryable),nextAttemptAt:row.next_attempt_at as Date|null}; },
};
