-- Phase 3: Operational domain rename — audit log presentation only.
-- Permission keys (operations:read, services:read, etc.) are resolved in application code;
-- no persisted permission rows require migration in this schema.
--
-- Historical audit_logs.entity_type values (inventory, store) are intentionally left
-- unchanged. The audit UI should map legacy labels at display time:
--   inventory → Operación
--   store     → Servicio
-- Do not mutate audit history in the database.
