import type { ProposedFix } from "./types";

const escapeSqlString = (value: string): string => value.replace(/'/g, "''");

const formatDecimal = (value: string): string => {
  const parsed = Number.parseFloat(value);
  if (!Number.isFinite(parsed)) {
    throw new Error(`Invalid decimal value: ${value}`);
  }

  return String(parsed);
};

const whereCurrentStore = (fix: ProposedFix): string => {
  if (!fix.dbId) {
    throw new Error(`Missing dbId for fix on store ${fix.storeNumber}`);
  }

  return `WHERE id = '${escapeSqlString(fix.dbId)}'
  AND name = N'${escapeSqlString(fix.storeNumber)}'`;
};

const buildCoordinateUpdateSql = (fix: ProposedFix): string => `UPDATE operational_locations
SET latitude = ${formatDecimal(fix.newLatitude)},
    longitude = ${formatDecimal(fix.newLongitude)},
    updated_at = SYSUTCDATETIME()
${whereCurrentStore(fix)};`;

const buildAddressUpdateSql = (fix: ProposedFix): string => `UPDATE operational_locations
SET address = N'${escapeSqlString(fix.newAddress)}',
    updated_at = SYSUTCDATETIME()
${whereCurrentStore(fix)};`;

const buildRenameSql = (fix: ProposedFix, newName: string): string => `UPDATE operational_locations
SET name = N'${escapeSqlString(newName)}',
    updated_at = SYSUTCDATETIME()
WHERE id = '${escapeSqlString(fix.dbId)}';`;

const buildDeactivateSql = (fix: ProposedFix): string => `UPDATE operational_locations
SET active = 0,
    updated_at = SYSUTCDATETIME()
${whereCurrentStore(fix)};`;

const buildInsertSql = (fix: ProposedFix, neighborhood: string, locality: string): string => `INSERT INTO operational_locations (
  name,
  address,
  neighborhood,
  locality,
  latitude,
  longitude,
  allowed_radius_meters,
  active,
  google_place_id,
  created_at,
  updated_at
)
VALUES (
  N'${escapeSqlString(fix.storeNumber)}',
  N'${escapeSqlString(fix.newAddress)}',
  ${neighborhood ? `N'${escapeSqlString(neighborhood)}'` : "NULL"},
  ${locality ? `N'${escapeSqlString(locality)}'` : "NULL"},
  ${formatDecimal(fix.newLatitude)},
  ${formatDecimal(fix.newLongitude)},
  150,
  1,
  NULL,
  SYSUTCDATETIME(),
  SYSUTCDATETIME()
);`;

export const buildSqlForFix = (
  fix: ProposedFix,
  context?: { neighborhood?: string; locality?: string },
): string => {
  switch (fix.fixType) {
    case "AUTO_FIX_COORDINATE":
    case "CRITICAL_COORDINATE_FIX":
    case "REVIEW_COORDINATE_FIX":
      return buildCoordinateUpdateSql(fix);
    case "AUTO_FIX_ADDRESS":
      return buildAddressUpdateSql(fix);
    case "RENAME_NONNUMERIC":
      return buildRenameSql(fix, fix.storeNumber);
    case "DEACTIVATE_DUPLICATE":
    case "DEACTIVATE_EXTRA":
      return buildDeactivateSql(fix);
    case "INSERT_MISSING":
      return buildInsertSql(fix, context?.neighborhood ?? "", context?.locality ?? "");
    default:
      throw new Error(`Unsupported fix type: ${fix.fixType}`);
  }
};

export const buildProposedSqlScript = (
  fixes: ProposedFix[],
  missingMeta: Map<string, { neighborhood: string; locality: string }>,
  environmentLabel: string,
): string => {
  const statements: string[] = [
    "-- Proposed store fixes generated by fix-stores-from-reconciliation.ts",
    `-- environment: ${environmentLabel}`,
    "-- Review carefully before applying.",
    "BEGIN TRANSACTION;",
    "",
  ];

  for (const fix of fixes) {
    statements.push(`-- ${fix.sqlComment}`);
    statements.push(`-- reason: ${fix.reason}`);
    if (fix.distanceMeters !== null) {
      statements.push(`-- distance_meters: ${fix.distanceMeters.toFixed(2)}`);
    }
    statements.push(
      buildSqlForFix(
        fix,
        fix.fixType === "INSERT_MISSING"
          ? missingMeta.get(fix.storeNumber)
          : undefined,
      ),
    );
    statements.push("");
  }

  statements.push("-- COMMIT TRANSACTION;");
  statements.push("ROLLBACK TRANSACTION;");
  return `${statements.join("\n")}\n`;
};
