export const ATTENDANCE_NOTIFICATION_TYPES = [
  "ARRIVAL_REMINDER_15_MIN",
  "EXIT_REMINDER_15_MIN",
  "NO_CHECKIN_AT_START",
  "ATTENDANCE_CONFIRMATION_REMINDER",
] as const;

export type AttendanceNotificationType = (typeof ATTENDANCE_NOTIFICATION_TYPES)[number];

export const ATTENDANCE_NOTIFICATION_STATUSES = [
  "PENDING",
  "SENT",
  "FAILED",
  "SENT_RECOVERY_REQUIRED",
  "SUPERSEDED",
] as const;

export type AttendanceNotificationStatus = (typeof ATTENDANCE_NOTIFICATION_STATUSES)[number];

export const ATTENDANCE_REMINDER_LEAD_MINUTES = 15;
export const ATTENDANCE_REMINDER_MAX_ATTEMPTS = 3;
export const ATTENDANCE_REMINDER_STALE_PENDING_MINUTES = 5;
export const NO_CHECKIN_AT_START_WINDOW_MINUTES = 1;

export const NO_LONGER_ELIGIBLE_FOR_NO_CHECKIN_AT_START =
  "NO_LONGER_ELIGIBLE_FOR_NO_CHECKIN_AT_START";

export const NO_LONGER_ELIGIBLE_FOR_ARRIVAL_REMINDER =
  "NO_LONGER_ELIGIBLE_FOR_ARRIVAL_REMINDER";

export const NO_LONGER_ELIGIBLE_FOR_EXIT_REMINDER =
  "NO_LONGER_ELIGIBLE_FOR_EXIT_REMINDER";

export const NO_LONGER_ELIGIBLE_FOR_CONFIRMATION_REMINDER =
  "NO_LONGER_ELIGIBLE_FOR_CONFIRMATION_REMINDER";

/** Send-time: employee already has a valid/pending check-in for the operation. */
export const NO_LONGER_ELIGIBLE_FOR_CONFIRMATION_ALREADY_CHECKED_IN =
  "NO_LONGER_ELIGIBLE_FOR_CONFIRMATION_ALREADY_CHECKED_IN";

/** Send-time: WAITING_LOCATION / WAITING_CHECKOUT_* must not be cancelled by confirmation. */
export const CONFIRMATION_BLOCKED_BY_ACTIVE_ATTENDANCE_SESSION =
  "CONFIRMATION_BLOCKED_BY_ACTIVE_ATTENDANCE_SESSION";

/**
 * Send-time: unique/active session conflict that is NOT proven to be a physical
 * attendance flow (do not report as CONFIRMATION_BLOCKED_BY_ACTIVE_ATTENDANCE_SESSION).
 */
export const CONFIRMATION_BLOCKED_BY_ACTIVE_SESSION_CONFLICT =
  "CONFIRMATION_BLOCKED_BY_ACTIVE_SESSION_CONFLICT";

export const SENT_CONTEXT_FAILED_ERROR = "SENT_CONTEXT_FAILED";

export const SENT_PERSISTENCE_UNKNOWN_ERROR = "SENT_PERSISTENCE_UNKNOWN";

export const ATTENDANCE_NOTIFICATION_TYPE_LABELS: Record<AttendanceNotificationType, string> = {
  ARRIVAL_REMINDER_15_MIN: "Recordatorio de llegada (15 min)",
  EXIT_REMINDER_15_MIN: "Recordatorio de salida (15 min)",
  NO_CHECKIN_AT_START: "Sin registro de ingreso al inicio",
  ATTENDANCE_CONFIRMATION_REMINDER: "Recordatorio de confirmación de asistencia",
};
