export const CHECKOUT_STATUSES = [
  "CHECKOUT_VALID",
  "CHECKOUT_EARLY_WITHIN_TOLERANCE",
  "CHECKOUT_EARLY_REVIEW",
  "CHECKOUT_LATE_EXTRA_TIME",
  "CHECKOUT_LOCATION_REVIEW",
  "CHECKOUT_REJECTED",
] as const;

export type CheckoutStatus = (typeof CHECKOUT_STATUSES)[number];
