export const WHATSAPP_FLOW_EXECUTION_STATUSES = [
  "STARTED",
  "COMPLETED",
  "FAILED",
  "PARTIALLY_RECORDED",
] as const;

export type WhatsappFlowExecutionStatus = (typeof WHATSAPP_FLOW_EXECUTION_STATUSES)[number];

export const WHATSAPP_FLOW_STEP_STATUSES = [
  "SUCCESS",
  "SKIPPED",
  "REJECTED",
  "WARNING",
  "FAILED",
] as const;

export type WhatsappFlowStepStatus = (typeof WHATSAPP_FLOW_STEP_STATUSES)[number];

export const WHATSAPP_CONVERSATION_STATUSES = ["ACTIVE", "COMPLETED", "WARNING", "ERROR"] as const;

export type WhatsappConversationStatus = (typeof WHATSAPP_CONVERSATION_STATUSES)[number];

export const WHATSAPP_FLOW_STEP_TYPES = [
  "WEBHOOK_RECEIVED",
  "SIGNATURE_VALIDATION",
  "IDEMPOTENCY_CHECK",
  "COMPANY_RESOLUTION",
  "PHONE_NORMALIZATION",
  "EMPLOYEE_RESOLUTION",
  "SESSION_RESOLUTION",
  "INTENT_DETECTION",
  "FLOW_ROUTING",
  "CANDIDATE_LOOKUP",
  "CANDIDATE_FILTER",
  "WORKDAY_SELECTION",
  "LOCATION_VALIDATION",
  "ATTENDANCE_CREATION",
  "CHECKOUT_CREATION",
  "ABSENCE_CREATION",
  "TEMPLATE_RESOLUTION",
  "MESSAGE_BUILD",
  "TWILIO_SEND",
  "TWILIO_STATUS_CALLBACK",
  "FLOW_COMPLETED",
  "ERROR",
] as const;

export type WhatsappFlowStepType = (typeof WHATSAPP_FLOW_STEP_TYPES)[number];

export const WHATSAPP_RESULT_CODES = {
  CHECKIN_LOCATION_REQUIRED: "CHECKIN_LOCATION_REQUIRED",
  CHECKIN_COMPLETED: "CHECKIN_COMPLETED",
  CHECKOUT_COMPLETED: "CHECKOUT_COMPLETED",
  NO_AVAILABLE_EMPLOYEE_WORKDAY: "NO_AVAILABLE_EMPLOYEE_WORKDAY",
  UNKNOWN_EMPLOYEE: "UNKNOWN_EMPLOYEE",
  AMBIGUOUS_COMPANY: "AMBIGUOUS_COMPANY",
  COMPANY_CONTEXT_UNAVAILABLE: "COMPANY_CONTEXT_UNAVAILABLE",
  NO_TODAY_ASSIGNMENTS: "NO_TODAY_ASSIGNMENTS",
  NO_UPCOMING_ASSIGNMENTS: "NO_UPCOMING_ASSIGNMENTS",
  INVALID_SELECTION: "INVALID_SELECTION",
  LOCATION_OUTSIDE_ALLOWED_RADIUS: "LOCATION_OUTSIDE_ALLOWED_RADIUS",
  LOCATION_REQUIRED: "LOCATION_REQUIRED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  MODULE_DISABLED: "MODULE_DISABLED",
  TEMPLATE_NOT_CONFIGURED: "TEMPLATE_NOT_CONFIGURED",
  TWILIO_SEND_FAILED: "TWILIO_SEND_FAILED",
  DUPLICATE_MESSAGE_SID: "DUPLICATE_MESSAGE_SID",
  IDEMPOTENT_REPLAY: "IDEMPOTENT_REPLAY",
  MENU_SHOWN: "MENU_SHOWN",
  WORKDAY_QUERY_COMPLETED: "WORKDAY_QUERY_COMPLETED",
  UPCOMING_ASSIGNMENTS_COMPLETED: "UPCOMING_ASSIGNMENTS_COMPLETED",
  PAYROLL_RECEIPT_PERIOD_REQUESTED: "PAYROLL_RECEIPT_PERIOD_REQUESTED",
  PAYROLL_RECEIPT_DELIVERED: "PAYROLL_RECEIPT_DELIVERED",
  PAYROLL_RECEIPT_NOT_FOUND: "PAYROLL_RECEIPT_NOT_FOUND",
  PAYROLL_RECEIPT_DELIVERY_UNAVAILABLE: "PAYROLL_RECEIPT_DELIVERY_UNAVAILABLE",
  PAYROLL_RECEIPT_CANCELLED: "PAYROLL_RECEIPT_CANCELLED",
  ABSENCE_FLOW: "ABSENCE_FLOW",
  CONFIRMATION_FLOW: "CONFIRMATION_FLOW",
  REMINDER_SENT: "REMINDER_SENT",
  REMINDER_FAILED: "REMINDER_FAILED",
  REMINDER_SKIPPED: "REMINDER_SKIPPED",
  PROVIDER_STATUS_RECORDED: "PROVIDER_STATUS_RECORDED",
  GENERIC_ERROR: "GENERIC_ERROR",
  FLOW_COMPLETED: "FLOW_COMPLETED",
} as const;

export type WhatsappResultCode =
  (typeof WHATSAPP_RESULT_CODES)[keyof typeof WHATSAPP_RESULT_CODES];

export const WHATSAPP_PROVIDER_STATUS_RANK: Record<string, number> = {
  accepted: 10,
  queued: 20,
  sending: 30,
  sent: 40,
  delivered: 50,
  read: 60,
  undelivered: 70,
  failed: 80,
  canceled: 90,
  cancelled: 90,
};
